services:
  - type: web
    name: backend-blogapp
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: Backend-BlogApp
    envVars:
      - key: DB_URL
        value: "REPLACE_WITH_YOUR_MONGODB_URI"
      - key: JWT_SECRET
        value: "REPLACE_WITH_A_STRONG_SECRET"
      - key: FRONTEND_URL
        value: "https://blogappfrontend-nine.vercel.app"
      - key: CLOUDINARY_URL
        value: "REPLACE_WITH_YOUR_CLOUDINARY_URL"
